### ISSUE TITLE
Raw autocmd not in augroup

### ISSUE THREAD

**Issue by yodigi7** [Djancyp/better-comments.nvim#1]
https://github.com/Djancyp/better-comments.nvim/blob/4ece622aae3f138c23f8c32344d70ae8c7cd2eb0/lua/better-comment/init.lua#L67

**Comment by Djancyp** [comment]
Can you explain what do you mean by this please ?

**Comment by yodigi7** [comment]
Every time I source my file it runs the setup function which will keep adding the autocmd and will cause performance issues if done enough times. Check out here for a better explanation, using autocmd groups will help solve the issue: https://learnvimscriptthehardway.stevelosh.com/chapters/14.html

**Comment by yodigi7** [comment]
Check out vim.api.nvim_create_augroup
