### ISSUE TITLE
Error with TS & nvim-tree.

### ISSUE THREAD

**Issue by AGou-ops** [Djancyp/better-comments.nvim#4]
default config: `require('better-comment').Setup()`
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/57939102/186203982-7cf2132b-3373-407b-a87a-5c946ea103a9.png">

**Comment by Djancyp** [comment]
I have add the fix . Can you update the plugin and let me know please.

**Comment by AGou-ops** [comment]
It works!
