### ISSUE TITLE
What's the difference between this plugin and todo-comments.nvim

### ISSUE THREAD

**Issue by Weissle** [Djancyp/better-comments.nvim#9]
This plugin seems to have the same feature as [todo-comments.nvim](https://github.com/folke/todo-comments.nvim).
I don't mean that this plugin is meaningless. On the contrary, if this plugin is better than or similar to todo-comments.nvim, I am happy to use it. Since todo-comments.nvim has no update for about half of the year.

**Comment by nagy135** [comment]
i have high hopes for this one as there is big issue i have with the other one and that is it breaks highlight on undo, shifts etc and doesnt seem to have much attention from maintainer.

The thing i totally miss here tho are those fancy highlights, i dont see why we should highlight entire line when only "TODO:" looks so much better imho. But i would really like author's opinion

**Comment by Djancyp** [comment]
Hey guys.
 I'm a huge fan of Unix philosophy. What does that mean?
I don't like over complicated apps plugins vs(personal opinion). I believe plugins has to do one thing but good and stable..

better-comments has only 123 line of code and does what it promise :)
